Fixes issue 132 (Public Suffix List (PSL) Updates Too Often)
dhs-ncats/trustymail pull request #133
Opened 2023-05-14 04:45 UTC by Matthew-Grayson

#  #

## 🗣 Description ##
Added code to set the PSL file's last modified time to reflect time of last download.

## 💭 Motivation and context ##
PSL should only be downloaded once per day. The current code attempts to enforce that by only downloading a new PSL, when the local copy is older than 24 hours:
```
psl_age = datetime.now() - datetime.fromtimestamp(
    stat(PublicSuffixListFilename).st_mtime
)
if psl_age > timedelta(hours=24):
    updatePSL(PublicSuffixListFilename)
```
stat.st_mtime checks the last modified date of the local PSL, however, the last modified date will often be 2-4 days ago  even if the PSL was downloaded minutes before.

## 🧪 Testing ##
I ran Trustymail against an array of domains.
The first domain was tested and then the code waited for a local PSL to be created before testing the remaining domains. I logged all STDOUT to see if the "PSL Updated" message appeared more than once.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-05-15 13:36 UTC, jsf9k requested changes
I'm requesting one very small change.

2023-05-15 13:36 UTC, jsf9k commented on src/trustymail/domain.py
> +
Remove needless blank line:
```suggestion
```

2023-05-15 14:31 UTC, jsf9k commented on src/trustymail/domain.py
> +
Fixed in commit e8726d8.

2023-05-15 14:42 UTC, jsf9k approved these changes

2023-05-15 15:13 UTC, dav3r approved these changes
LGTM 👍

2023-09-12 14:26 UTC, jsf9k commented
I also did some testing with these changes and verified that they function as expected.

2023-09-12 14:26 UTC, merged